### ISSUE TITLE
大佬，如何Python 推理？

### ISSUE THREAD

**Issue by huangwgang** [heyongxin233/YOLO-Pruning-RKNN#2]

**Comment by heyongxin233** [comment]
你可以使用该项目中的infer.py推理，具体可以参考文档[Predict](https://docs.ultralytics.com/modes/predict/)，如果想使用瑞芯微的开发板推理，可以参考[rknn_yolov8](https://github.com/airockchip/rknn_model_zoo/blob/main/examples/yolov8/README.md)

**Comment by huangwgang** [comment]
大佬，单类别评估模型如何操作？

**Comment by heyongxin233** [comment]
你说说的是把所有类别当成一类吗，你可以在训练的时候加入参数single_cls=True，具体你可以看https://docs.ultralytics.com/usage/cfg/#train
